-- 1. zadatak I nacin
SELECT FILM.NASLOV, REZISER.IME, PREZIME
FROM FILM INNER JOIN REZISER ON FILM.REZISER = REZISER.BROJ;

-- II nacin

SELECT FILM.NASLOV, REZISER.IME, REZISER.PREZIME
FROM FILM, REZISER
WHERE FILM.REZISER = REZISER.BROJ;
