SELECT BROJ, NASLOV
FROM FILM
WHERE TIP = 'comedy' AND ( AA_NAGRADE IS NOT NULL OR AA_NAGRADE > 0 ) AND LOWER(NASLOV) NOT LIKE '%uncle%' AND GODINA > 1970;

-- ovde je NOT LIKE moglo da se iskoristi i ovako

SELECT BROJ, NASLOV
FROM FILM
WHERE TIP = 'comedy' AND ( AA_NAGRADE IS NOT NULL OR AA_NAGRADE > 0 ) AND NOT LOWER(NASLOV) LIKE '%uncle%' AND GODINA > 1970;
