-- 1. zadatak
CREATE VIEW STATISTIKA_RADNIH_MESTA
AS
SELECT
  Z.IME,
  Z.PREZIME,
  COUNT(DISTINCT IRM.ID_R_MESTO) AS BROJ_R_MESTA,
  SUM(IRM.DATUM_KRAJA - IRM.DAYUM_POC) AS VREME
FROM
  ZAPOSLENI Z
INNER JOIN
  ISTORIJA_RADNIH_MESTA IRM
INNER JOIN
  Z.ID = IRM.ID_ZAP;


SELECT *
FROM
  STATISTIKA_RADNIH_MESTA
WHERE
  VREME > 100
AND
  BROJ_R_MESTA >= 2;

-- 2. zadatak
-- ovaj VIEW uzima sva odeljenja koja imaju najmanje 2 zaposlena
CREATE VIEW ODELJENJE_ZAPOSLENI
AS
SELECT
  Z.ID_ODELJENJE
FROM
  ZAPOSLENI Z
GROUP BY
  Z.ID_ODELJENJE
HAVING
  COUNT(*) >= 2;


UPDATE
  ZAPOSLENI Z
SET
  PLATA = PLATA * 1.15
WHERE EXISTS
  (SELECT 1
  FROM
    RADNO_MESTO RM, ODELJENJE_ZAPOSLENI OZ
  WHERE
    RM.ID = Z.ID_R_MESTO
  AND
    OZ.ID_ODELJENJE = Z.ID_ODELJENJE
  AND
    RM.MAX_PLATA < 70000
  AND
    OZ.ID_ODELJENJE = Z.ID_ODELJENJE);


-- 3. zadatak
DELETE FROM
  ISTORIJA_RADNIH_MESTA IRM
WHERE NOT EXISTS
  (SELECT 1
  FROM
    ZAPOSLENI Z
  WHERE
    Z.ID_R_MESTO = IRM.ID_R_MESTO);
