SELECT FILM.BROJ, NASLOV
FROM FILM INNER JOIN REZISER ON FILM.REZISER = REZISER.BROJ
WHERE REZISER.IME = 'Emir' AND REZISER.PREZIME = 'Kusturica'
MINUS
SELECT FILM.BROJ, NASLOV
FROM FILM INNER JOIN IGRA ON FILM.BROJ = IGRA.FILM
  INNER JOIN GLUMAC ON GLUMAC.BROJ = IGRA.GLUMAC
WHERE GLUMAC.IME = 'Mira' AND GLUMAC.PREZIME = 'Banjac';
